/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JLabel;

/**
 *
 * @author ester
 */
public class Tela_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Ececucao
     */
    public Tela_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_cabecalho = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel_Menu = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        detalhes_pesquisar = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Receita3 = new javax.swing.JLabel();
        Receita4 = new javax.swing.JLabel();
        Receita5 = new javax.swing.JLabel();
        Receita7 = new javax.swing.JLabel();
        Receita8 = new javax.swing.JLabel();
        Receita9 = new javax.swing.JLabel();
        ButtonMaisReceitas = new javax.swing.JLabel();
        Receita2 = new javax.swing.JLabel();
        Receita1 = new javax.swing.JLabel();
        Receita6 = new javax.swing.JLabel();
        btAdicionarReceita = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();

        jLabel13.setBackground(new java.awt.Color(110, 198, 202));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Receita 1");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(8, 151, 157));

        jPanel_cabecalho.setBackground(new java.awt.Color(8, 151, 157));
        jPanel_cabecalho.setForeground(new java.awt.Color(8, 151, 157));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Cook Tok");

        jPanel_Menu.setBackground(new java.awt.Color(204, 171, 216));
        jPanel_Menu.setForeground(new java.awt.Color(204, 171, 216));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtro", "Ingrediente", "Nome", "Tempo" }));

        detalhes_pesquisar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        detalhes_pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        detalhes_pesquisar.setText("Pesquisar");

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detalhes_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detalhes_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(204, 171, 216));
        jPanel3.setForeground(new java.awt.Color(204, 171, 216));

        jPanel6.setBackground(new java.awt.Color(110, 198, 202));

        Receita3.setBackground(new java.awt.Color(110, 198, 202));
        Receita3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita3.setForeground(new java.awt.Color(255, 255, 255));
        Receita3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita3.setText("Receita 1");
        Receita3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Receita4.setBackground(new java.awt.Color(110, 198, 202));
        Receita4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita4.setForeground(new java.awt.Color(255, 255, 255));
        Receita4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita4.setText("Receita 1");
        Receita4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Receita5.setBackground(new java.awt.Color(110, 198, 202));
        Receita5.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita5.setForeground(new java.awt.Color(255, 255, 255));
        Receita5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita5.setText("Receita 1");
        Receita5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Receita7.setBackground(new java.awt.Color(110, 198, 202));
        Receita7.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita7.setForeground(new java.awt.Color(255, 255, 255));
        Receita7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita7.setText("Receita 1");
        Receita7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Receita8.setBackground(new java.awt.Color(110, 198, 202));
        Receita8.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita8.setForeground(new java.awt.Color(255, 255, 255));
        Receita8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita8.setText("Receita 1");
        Receita8.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Receita9.setBackground(new java.awt.Color(110, 198, 202));
        Receita9.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita9.setForeground(new java.awt.Color(255, 255, 255));
        Receita9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita9.setText("Receita 1");
        Receita9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ButtonMaisReceitas.setBackground(new java.awt.Color(110, 198, 202));
        ButtonMaisReceitas.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        ButtonMaisReceitas.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMaisReceitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonMaisReceitas.setText("+");
        ButtonMaisReceitas.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        ButtonMaisReceitas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonMaisReceitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Receita2.setBackground(new java.awt.Color(110, 198, 202));
        Receita2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita2.setForeground(new java.awt.Color(255, 255, 255));
        Receita2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita2.setText("Receita 2");
        Receita2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Receita1.setBackground(new java.awt.Color(110, 198, 202));
        Receita1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita1.setForeground(new java.awt.Color(255, 255, 255));
        Receita1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita1.setText("Receita 1");
        Receita1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Receita1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Receita1MouseEntered(evt);
            }
        });

        Receita6.setBackground(new java.awt.Color(110, 198, 202));
        Receita6.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        Receita6.setForeground(new java.awt.Color(255, 255, 255));
        Receita6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receita6.setText("Receita 1");
        Receita6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        Receita6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Receita6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Receita1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Receita6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Receita7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Receita2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Receita3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Receita8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Receita4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Receita9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Receita5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMaisReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Receita4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Receita5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Receita9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonMaisReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(Receita3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Receita8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(Receita7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Receita1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Receita2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Receita6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btAdicionarReceita.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btAdicionarReceita.setText("Adicionar \nReceitas");
        btAdicionarReceita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAdicionarReceita.setInheritsPopupMenu(true);
        btAdicionarReceita.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btAdicionarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_cabecalhoLayout = new javax.swing.GroupLayout(jPanel_cabecalho);
        jPanel_cabecalho.setLayout(jPanel_cabecalhoLayout);
        jPanel_cabecalhoLayout.setHorizontalGroup(
            jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                .addGroup(jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAdicionarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_cabecalhoLayout.setVerticalGroup(
            jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(btAdicionarReceita))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Receita1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Receita1MouseEntered
       
    }//GEN-LAST:event_Receita1MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btAdicionarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarReceitaActionPerformed
        setEnabled(false);
        new TelaAdicionar_Ingrediente_Receita().setVisible(true);
    }//GEN-LAST:event_btAdicionarReceitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonMaisReceitas;
    private javax.swing.JLabel Receita1;
    private javax.swing.JLabel Receita2;
    private javax.swing.JLabel Receita3;
    private javax.swing.JLabel Receita4;
    private javax.swing.JLabel Receita5;
    private javax.swing.JLabel Receita6;
    private javax.swing.JLabel Receita7;
    private javax.swing.JLabel Receita8;
    private javax.swing.JLabel Receita9;
    private javax.swing.JButton btAdicionarReceita;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel detalhes_pesquisar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_cabecalho;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
