/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ConexaoFactory;
import cookTok.Receita;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author ester
 */
public class Tela_Inicio extends javax.swing.JFrame {
    private int[] vetorCodigo = new int[10];
    private Tela_Exec telaExec;
    private int pagina = 0; 
    private ArrayList<Receita> lista;
    /**
     * Creates new form Tela_Ececucao
     */
    public Tela_Inicio() {
        initComponents();
        this.telaExec = new Tela_Exec();
        this.lista = new ArrayList<>();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        popup = new javax.swing.JDialog();
        mensagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_cabecalho = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel_Menu = new javax.swing.JPanel();
        cbFiltro = new javax.swing.JComboBox<>();
        detalhes_pesquisar = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        cbOrdem = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        pReceitas = new javax.swing.JPanel();
        lbReceita2 = new javax.swing.JLabel();
        lbReceita3 = new javax.swing.JLabel();
        lbReceita4 = new javax.swing.JLabel();
        lbReceita6 = new javax.swing.JLabel();
        lbReceita7 = new javax.swing.JLabel();
        lbReceita8 = new javax.swing.JLabel();
        lbReceita9 = new javax.swing.JLabel();
        lbReceita0 = new javax.swing.JLabel();
        lbReceita1 = new javax.swing.JLabel();
        lbReceita5 = new javax.swing.JLabel();
        btAdicionarReceita = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        btAvancar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        jLabel13.setBackground(new java.awt.Color(110, 198, 202));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Receita 1");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout popupLayout = new javax.swing.GroupLayout(popup.getContentPane());
        popup.getContentPane().setLayout(popupLayout);
        popupLayout.setHorizontalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        popupLayout.setVerticalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Tela_Exec"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(8, 151, 157));

        jPanel_cabecalho.setBackground(new java.awt.Color(8, 151, 157));
        jPanel_cabecalho.setForeground(new java.awt.Color(8, 151, 157));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Cook Tok");

        jPanel_Menu.setBackground(new java.awt.Color(204, 171, 216));
        jPanel_Menu.setForeground(new java.awt.Color(204, 171, 216));

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nome iniciando por", "Tempo(min) maior que", "Tempo(min) menor que", "Ingrediente iniciando por" }));
        cbFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFiltroItemStateChanged(evt);
            }
        });

        detalhes_pesquisar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        detalhes_pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        detalhes_pesquisar.setText("Pesquisar");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        cbOrdem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-Z", "Z-A", "Maior tempo", "Menor tempo" }));

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MenuLayout.createSequentialGroup()
                        .addComponent(detalhes_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_MenuLayout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addComponent(detalhes_pesquisar)
                .addGap(3, 3, 3)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 171, 216));
        jPanel3.setForeground(new java.awt.Color(204, 171, 216));

        pReceitas.setBackground(new java.awt.Color(110, 198, 202));

        lbReceita2.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita2.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita2.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita2MouseClicked(evt);
            }
        });

        lbReceita3.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita3.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita3.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita3MouseClicked(evt);
            }
        });

        lbReceita4.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita4.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita4.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita4MouseClicked(evt);
            }
        });

        lbReceita6.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita6.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita6.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita6MouseClicked(evt);
            }
        });

        lbReceita7.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita7.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita7.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita7MouseClicked(evt);
            }
        });

        lbReceita8.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita8.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita8.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita8.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita8MouseClicked(evt);
            }
        });

        lbReceita9.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita9.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita9.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita9MouseClicked(evt);
            }
        });

        lbReceita0.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita0.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita0.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita0.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita0MouseClicked(evt);
            }
        });

        lbReceita1.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita1.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita1MouseClicked(evt);
            }
        });

        lbReceita5.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita5.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lbReceita5.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pReceitasLayout = new javax.swing.GroupLayout(pReceitas);
        pReceitas.setLayout(pReceitasLayout);
        pReceitasLayout.setHorizontalGroup(
            pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReceitasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbReceita6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbReceita8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbReceita0, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbReceita2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbReceita4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pReceitasLayout.createSequentialGroup()
                        .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbReceita7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbReceita1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbReceita9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(pReceitasLayout.createSequentialGroup()
                        .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbReceita5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbReceita3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pReceitasLayout.setVerticalGroup(
            pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReceitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbReceita0, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lbReceita1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbReceita2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(lbReceita3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbReceita5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbReceita4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pReceitasLayout.createSequentialGroup()
                        .addGroup(pReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbReceita6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(lbReceita7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lbReceita8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbReceita9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btAdicionarReceita.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btAdicionarReceita.setText("Adicionar \nReceitas");
        btAdicionarReceita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAdicionarReceita.setInheritsPopupMenu(true);
        btAdicionarReceita.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btAdicionarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_cabecalhoLayout = new javax.swing.GroupLayout(jPanel_cabecalho);
        jPanel_cabecalho.setLayout(jPanel_cabecalhoLayout);
        jPanel_cabecalhoLayout.setHorizontalGroup(
            jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAdicionarReceita)
                .addGap(113, 113, 113))
        );
        jPanel_cabecalhoLayout.setVerticalGroup(
            jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulo)
                    .addComponent(btAdicionarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btAvancar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btAvancar.setText(">");
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btVoltar.setText("<");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_cabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAvancar)
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        //Pegar filtro do COmboBox e do campo de texto
        String sql = "SELECT * from dbcooktok.tbreceita r " +
                     " inner join tbrelingrerec rel on r.pkcodreceita = rel.fkcodreceita " +
                     " inner join tbingrediente i on i.pkcodingre = rel.fkcodingre ";
        String condicao;
        condicao = txtPesquisar.getText();
        int cond;
        if(condicao != ""){
            switch(cbFiltro.getSelectedIndex()){
                case 0:
                    break;
                case 1:
                    sql = sql+" where upper(r.nomereceita) like upper('"+condicao+"%')";
                    break;
                case 2:
                    cond = Integer.parseInt(condicao);
                    sql = sql+" where r.tempo >"+cond*60;
                    break;
                case 3:
                    cond = Integer.parseInt(condicao);
                    sql = sql+" where r.tempo <"+cond*60;
                    break;
                case 4:
                    sql = sql+" where upper(i.nomeingre) like upper('"+condicao+"%')";
                    break;
            }
        }
        
        sql = sql + " group by r.pkcodreceita";
        
        switch(cbOrdem.getSelectedIndex()){
                case 0:
                    sql = sql+" order by r.nomereceita";
                    break;
                case 1:
                    sql = sql+" order by r.nomereceita desc";
                    break;
                case 2:
                    sql = sql+" order by r.tempo desc";
                    break;
                case 3:
                    sql = sql+" order by r.tempo";
                    break;
            }
        
        pagina = 0;
        btVoltar.setEnabled(false);
        carregaReceitas(sql);
        exibeLista();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btAdicionarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarReceitaActionPerformed
        new TelaAdicionar_Receita().setVisible(true);
    }//GEN-LAST:event_btAdicionarReceitaActionPerformed

    private void lbReceita0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita0MouseClicked
        if (vetorCodigo[0] != -1){
            telaExec.setCodReceita(vetorCodigo[0]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita0MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        btVoltar.setEnabled(false);
        String sql = "SELECT * from dbcooktok.tbreceita order by nomereceita";
        carregaReceitas(sql);
        exibeLista();
    }//GEN-LAST:event_formWindowActivated

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        pagina++;
        btVoltar.setEnabled(true);
        exibeLista();
    }//GEN-LAST:event_btAvancarActionPerformed

    private void lbReceita1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita1MouseClicked
        if (vetorCodigo[1] != -1){
            telaExec.setCodReceita(vetorCodigo[1]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita1MouseClicked

    private void lbReceita2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita2MouseClicked
        if (vetorCodigo[2] != -1){
            telaExec.setCodReceita(vetorCodigo[2]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita2MouseClicked

    private void lbReceita3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita3MouseClicked
        if (vetorCodigo[3] != -1){
            telaExec.setCodReceita(vetorCodigo[3]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita3MouseClicked

    private void lbReceita4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita4MouseClicked
        if (vetorCodigo[4] != -1){
            telaExec.setCodReceita(vetorCodigo[4]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita4MouseClicked

    private void lbReceita5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita5MouseClicked
        if (vetorCodigo[5] != -1){
            telaExec.setCodReceita(vetorCodigo[5]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita5MouseClicked

    private void lbReceita6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita6MouseClicked
        if (vetorCodigo[6] != -1){
            telaExec.setCodReceita(vetorCodigo[6]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita6MouseClicked

    private void lbReceita7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita7MouseClicked
        if (vetorCodigo[7] != -1){
            telaExec.setCodReceita(vetorCodigo[7]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita7MouseClicked

    private void lbReceita8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita8MouseClicked
        if (vetorCodigo[8] != -1){
            telaExec.setCodReceita(vetorCodigo[8]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita8MouseClicked

    private void lbReceita9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita9MouseClicked
        if (vetorCodigo[9] != -1){
            telaExec.setCodReceita(vetorCodigo[9]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita9MouseClicked

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        btAvancar.setEnabled(true);
        pagina--;
        if(pagina == 0){
            btVoltar.setEnabled(false);
        }
        exibeLista();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void cbFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFiltroItemStateChanged
        txtPesquisar.setText("");
    }//GEN-LAST:event_cbFiltroItemStateChanged
    
    public void carregaReceitas(String sql){   
        lista.clear();  
        try {
            Connection conn = ConexaoFactory.getConexao();
            Statement stat = conn.createStatement();
            
            ResultSet result = stat.executeQuery(sql);
            
            
            while(result.next()){
                Receita rec = new Receita(result.getInt("pkcodreceita"), result.getString("nomereceita"), result.getInt("tempo"));
                lista.add(rec);
            }           
            ConexaoFactory.close(conn,stat);
        } catch (SQLException throwables) {
            System.out.println("Erro ao carregar Receitas");
        }
    }
    
    public void exibeLista(){        
        //Limpa os Labels
        for(int i=0; i<pReceitas.getComponentCount(); i++){
            if(pReceitas.getComponent(i) instanceof JLabel){        
                JLabel label =(JLabel)pReceitas.getComponent(i);               
                label.setText("");               
            }
        }
        int cont = (pagina*10);
        Receita rec = new Receita();
        limpaVetor();

        try{
            rec = lista.get(cont);
            lbReceita0.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[0] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita1.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[1] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita2.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[2] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita3.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[3] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita4.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[4] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita5.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[5] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita6.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[6] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita7.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[7] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita8.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[8] = rec.getCod_Receita();
            cont++;

            rec = lista.get(cont);
            lbReceita9.setText(rec.getNome_Receita()+"  "+formataTempo(rec.getTempo_Preparo()));
            vetorCodigo[9] = rec.getCod_Receita(); 
        }catch(IndexOutOfBoundsException e){
            btAvancar.setEnabled(false);
        }
    }
    
    public String formataTempo(int t){
        int minuto = ((t % 3600) / 60);
        int hora = (t / 3600);
        return String.format("%02dh%02dmin", hora, minuto);
    }
    
    public void limpaVetor(){
        for(int i=0; i < vetorCodigo.length; i++){
            vetorCodigo[i]= -1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarReceita;
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btVoltar;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JComboBox<String> cbOrdem;
    private javax.swing.JLabel detalhes_pesquisar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_cabecalho;
    private javax.swing.JLabel lbReceita0;
    private javax.swing.JLabel lbReceita1;
    private javax.swing.JLabel lbReceita2;
    private javax.swing.JLabel lbReceita3;
    private javax.swing.JLabel lbReceita4;
    private javax.swing.JLabel lbReceita5;
    private javax.swing.JLabel lbReceita6;
    private javax.swing.JLabel lbReceita7;
    private javax.swing.JLabel lbReceita8;
    private javax.swing.JLabel lbReceita9;
    private javax.swing.JLabel mensagem;
    private javax.swing.JPanel pReceitas;
    private javax.swing.JDialog popup;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
