/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ConexaoFactory;
import cookTok.Ingrediente;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ester
 */
public class TelaAdicionar_Ingrediente_Receita extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionar_Ingrediente_Receita
     */
    public TelaAdicionar_Ingrediente_Receita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Poupop = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        OK = new javax.swing.JButton();
        mensagem_de_alerta = new javax.swing.JLabel();
        PainelFundo = new javax.swing.JPanel();
        PainelCabecalho = new javax.swing.JPanel();
        cabecalho_Nome = new javax.swing.JLabel();
        cbCodIngrediente = new javax.swing.JComboBox<>();
        PainelNomeReceita = new javax.swing.JPanel();
        txtNome_Receita = new javax.swing.JTextField();
        descricao_nome_receita = new javax.swing.JLabel();
        PainelIngredientes = new javax.swing.JPanel();
        descricao_indgredientes = new javax.swing.JLabel();
        descricao_ingredientes_quantidade = new javax.swing.JLabel();
        descricao_ingredientes_unidadedemedida = new javax.swing.JLabel();
        txtCombo_Box_ingredientes = new javax.swing.JComboBox<>();
        txtIngrediente_Quantidade = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btAdicionarIngrediente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_de_ingredientes = new javax.swing.JTable();
        btExcluirIngrediente = new javax.swing.JButton();
        PainelRodapé = new javax.swing.JPanel();
        Button_Salvar = new javax.swing.JButton();
        PainelInstrucoes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNomeInstru = new javax.swing.JTextArea();
        lbInstrucao = new javax.swing.JLabel();
        lbTempo = new javax.swing.JLabel();
        txtTempoInstru = new javax.swing.JTextField();
        btAdicionarInstrucao = new javax.swing.JButton();
        btExcluirInstrucao = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_de_instrucoes = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Poupop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(8, 151, 157));

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        mensagem_de_alerta.setBackground(new java.awt.Color(255, 255, 255));
        mensagem_de_alerta.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mensagem_de_alerta.setForeground(new java.awt.Color(255, 255, 255));
        mensagem_de_alerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagem_de_alerta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mensagem_de_alerta.setFocusCycleRoot(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(OK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(mensagem_de_alerta, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(mensagem_de_alerta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OK)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout PoupopLayout = new javax.swing.GroupLayout(Poupop.getContentPane());
        Poupop.getContentPane().setLayout(PoupopLayout);
        PoupopLayout.setHorizontalGroup(
            PoupopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoupopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PoupopLayout.setVerticalGroup(
            PoupopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoupopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PainelFundo.setBackground(new java.awt.Color(8, 151, 157));

        PainelCabecalho.setBackground(new java.awt.Color(8, 151, 157));
        PainelCabecalho.setForeground(new java.awt.Color(204, 204, 255));

        cabecalho_Nome.setBackground(new java.awt.Color(25, 236, 243));
        cabecalho_Nome.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        cabecalho_Nome.setForeground(new java.awt.Color(255, 255, 255));
        cabecalho_Nome.setText("Cook Tok");

        cbCodIngrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x", "x" }));
        cbCodIngrediente.setName("cbCodIngrediente");
        cbCodIngrediente.setVisible(false);

        javax.swing.GroupLayout PainelCabecalhoLayout = new javax.swing.GroupLayout(PainelCabecalho);
        PainelCabecalho.setLayout(PainelCabecalhoLayout);
        PainelCabecalhoLayout.setHorizontalGroup(
            PainelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCabecalhoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cabecalho_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbCodIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        PainelCabecalhoLayout.setVerticalGroup(
            PainelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cabecalho_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(cbCodIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PainelNomeReceita.setBackground(new java.awt.Color(204, 171, 216));

        descricao_nome_receita.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        descricao_nome_receita.setForeground(new java.awt.Color(255, 255, 255));
        descricao_nome_receita.setText("Nome da Receita:");

        javax.swing.GroupLayout PainelNomeReceitaLayout = new javax.swing.GroupLayout(PainelNomeReceita);
        PainelNomeReceita.setLayout(PainelNomeReceitaLayout);
        PainelNomeReceitaLayout.setHorizontalGroup(
            PainelNomeReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNomeReceitaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PainelNomeReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricao_nome_receita)
                    .addComponent(txtNome_Receita, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelNomeReceitaLayout.setVerticalGroup(
            PainelNomeReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelNomeReceitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descricao_nome_receita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome_Receita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        PainelIngredientes.setBackground(new java.awt.Color(110, 198, 202));

        descricao_indgredientes.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        descricao_indgredientes.setForeground(new java.awt.Color(255, 255, 255));
        descricao_indgredientes.setText("Ingrediente:");

        descricao_ingredientes_quantidade.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        descricao_ingredientes_quantidade.setForeground(new java.awt.Color(255, 255, 255));
        descricao_ingredientes_quantidade.setText("Quantidade");

        descricao_ingredientes_unidadedemedida.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        descricao_ingredientes_unidadedemedida.setForeground(new java.awt.Color(255, 255, 255));
        descricao_ingredientes_unidadedemedida.setText("Unidade de Medida");

        txtCombo_Box_ingredientes.setBackground(new java.awt.Color(204, 204, 255));
        txtCombo_Box_ingredientes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtCombo_Box_ingredientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Adicionar novo" }));
        txtCombo_Box_ingredientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCombo_Box_ingredientesFocusLost(evt);
            }
        });

        txtIngrediente_Quantidade.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtIngrediente_Quantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIngrediente_Quantidade.setText("0");

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidade", "kg", "g", "ml ", "l", "uni." }));

        btAdicionarIngrediente.setBackground(new java.awt.Color(204, 171, 216));
        btAdicionarIngrediente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btAdicionarIngrediente.setText("Adicionar");
        btAdicionarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarIngredienteActionPerformed(evt);
            }
        });

        tabela_de_ingredientes.setBackground(new java.awt.Color(204, 204, 255));
        tabela_de_ingredientes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tabela_de_ingredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingredientes", "Quantidade", "Unidade de Medida"
            }
        ));
        tabela_de_ingredientes.setCellSelectionEnabled(true);
        tabela_de_ingredientes.setEditingRow(0);
        tabela_de_ingredientes.setEnabled(false);
        jScrollPane2.setViewportView(tabela_de_ingredientes);

        btExcluirIngrediente.setBackground(new java.awt.Color(204, 204, 255));
        btExcluirIngrediente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btExcluirIngrediente.setText("Excluir");
        btExcluirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelIngredientesLayout = new javax.swing.GroupLayout(PainelIngredientes);
        PainelIngredientes.setLayout(PainelIngredientesLayout);
        PainelIngredientesLayout.setHorizontalGroup(
            PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelIngredientesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelIngredientesLayout.createSequentialGroup()
                        .addGroup(PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelIngredientesLayout.createSequentialGroup()
                                .addGap(418, 418, 418)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addGroup(PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btExcluirIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAdicionarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(70, 70, 70))
                    .addGroup(PainelIngredientesLayout.createSequentialGroup()
                        .addGroup(PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricao_indgredientes)
                            .addComponent(txtCombo_Box_ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricao_ingredientes_quantidade)
                            .addGroup(PainelIngredientesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtIngrediente_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(descricao_ingredientes_unidadedemedida)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PainelIngredientesLayout.setVerticalGroup(
            PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricao_indgredientes)
                    .addComponent(descricao_ingredientes_quantidade)
                    .addComponent(descricao_ingredientes_unidadedemedida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCombo_Box_ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngrediente_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PainelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelIngredientesLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btExcluirIngrediente))
                    .addGroup(PainelIngredientesLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        PainelRodapé.setBackground(new java.awt.Color(110, 198, 202));

        Button_Salvar.setBackground(new java.awt.Color(204, 204, 255));
        Button_Salvar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Button_Salvar.setText("Salvar");
        Button_Salvar.setToolTipText("");
        Button_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelRodapéLayout = new javax.swing.GroupLayout(PainelRodapé);
        PainelRodapé.setLayout(PainelRodapéLayout);
        PainelRodapéLayout.setHorizontalGroup(
            PainelRodapéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRodapéLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        PainelRodapéLayout.setVerticalGroup(
            PainelRodapéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRodapéLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Salvar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PainelInstrucoes.setBackground(new java.awt.Color(204, 171, 216));

        txtNomeInstru.setColumns(20);
        txtNomeInstru.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomeInstru.setRows(5);
        jScrollPane3.setViewportView(txtNomeInstru);

        lbInstrucao.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lbInstrucao.setForeground(new java.awt.Color(255, 255, 255));
        lbInstrucao.setText("Instrução:");

        lbTempo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lbTempo.setForeground(new java.awt.Color(255, 255, 255));
        lbTempo.setText("Tempo de execução:");

        txtTempoInstru.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempoInstru.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTempoInstru.setText("0");

        btAdicionarInstrucao.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btAdicionarInstrucao.setText("Adicionar");
        btAdicionarInstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarInstrucaoActionPerformed(evt);
            }
        });

        btExcluirInstrucao.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btExcluirInstrucao.setText("Excluir");
        btExcluirInstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirInstrucaoActionPerformed(evt);
            }
        });

        tabela_de_instrucoes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tabela_de_instrucoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Instrução", "Tempo(min)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela_de_instrucoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tabela_de_instrucoes);

        javax.swing.GroupLayout PainelInstrucoesLayout = new javax.swing.GroupLayout(PainelInstrucoes);
        PainelInstrucoes.setLayout(PainelInstrucoesLayout);
        PainelInstrucoesLayout.setHorizontalGroup(
            PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                        .addGroup(PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbInstrucao)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lbTempo))
                            .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(txtTempoInstru, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btExcluirInstrucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAdicionarInstrucao, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        PainelInstrucoesLayout.setVerticalGroup(
            PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                .addGroup(PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelInstrucoesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbInstrucao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInstrucoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTempo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelInstrucoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTempoInstru, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInstrucoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAdicionarInstrucao)
                .addGap(52, 52, 52)
                .addComponent(btExcluirInstrucao)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout PainelFundoLayout = new javax.swing.GroupLayout(PainelFundo);
        PainelFundo.setLayout(PainelFundoLayout);
        PainelFundoLayout.setHorizontalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PainelRodapé, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelInstrucoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelNomeReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelFundoLayout.setVerticalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(PainelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelNomeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelRodapé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Button_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SalvarActionPerformed
        Ingrediente ingrediente = new Ingrediente();
        if (txtNome_Receita.getText().isEmpty()) {
            Poupop.setSize(400, 200);
            mensagem_de_alerta.setText("Digite nome da receita!");
            Poupop.setVisible(true);
        } else if (tabela_de_ingredientes.getRowCount()==0){
            Poupop.setSize(400, 200);
            mensagem_de_alerta.setText("Adicione uma ingrediente!");
            Poupop.setVisible(true);
        } else if (tabela_de_instrucoes.getRowCount()==0){
            Poupop.setSize(400, 200);
            mensagem_de_alerta.setText("Adicione uma instrução!");
            Poupop.setVisible(true);
        }else {
            Poupop.setSize(400, 200);
            ingrediente.setNome_Ingred((txtNome_Receita.getText()));
            mensagem_de_alerta.setText(ingrediente.getNome_Ingred());
            Poupop.add(mensagem_de_alerta);
            Poupop.setVisible(true);
        }
        
        int tempo = 0;
        for(int linha=0; linha<tabela_de_instrucoes.getRowCount();linha++){
            tempo = tempo + (Integer)tabela_de_instrucoes.getModel().getValueAt(linha, 1);
        }
        
        String sql = "INSERT INTO dbcooktok.tbreceita (nomereceita, tempo)"
                + "VALUES ('"+txtNome_Receita.getText()
                +"',"+tempo+")";
        System.out.println(sql);
        try {
            Connection conn = ConexaoFactory.getConexao();
            Statement stat = conn.createStatement();
            
           stat.execute(sql);
                int codigo = 1;
                sql = "SELECT max(pkcodreceita) as maior from dbcooktok.tbreceita";
                System.out.println(sql);
                ResultSet resultado = stat.executeQuery(sql);
                while(resultado.next()){
                    codigo = resultado.getInt("maior");
                
                /*      PRECISA MUDAR A TABELA
                for(int linha=0; linha<tabela_de_ingredientes.getRowCount();linha++){
                    sql = "INSERT INTO dbcooktok.tbrelingrerec (fkcodreceita, fkcodingre, )"
                    + "VALUES ('"+tabela_de_instrucoes.getModel().getValueAt(linha, 0)
                    +"',"+tabela_de_instrucoes.getModel().getValueAt(linha, 1)
                    +","+codigo+")";
                    
                }*/
                
                for(int linha=0; linha<tabela_de_instrucoes.getRowCount();linha++){
                    sql = "INSERT INTO dbcooktok.tbintrucoes (nomeinstru, tempoinstru, fkcodreceita)"
                    + "VALUES ('"+tabela_de_instrucoes.getModel().getValueAt(linha, 0)
                    +"',"+tabela_de_instrucoes.getModel().getValueAt(linha, 1)
                    +","+codigo+")";
                    stat.execute(sql);
                }
            }
            
            ConexaoFactory.close(conn,stat);
        } catch (SQLException throwables) {
            System.out.println("Erro ao inserir Receita");
        } 
    }//GEN-LAST:event_Button_SalvarActionPerformed
    
 
    private void btAdicionarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarIngredienteActionPerformed
        String ingre = (String) txtCombo_Box_ingredientes.getSelectedItem();
        int quantidade = Integer.parseInt(txtIngrediente_Quantidade.getText());
        String unidade = (String) jComboBox1.getSelectedItem();
        
        if (ingre.equals("Selecione")) {
            Poupop.setSize(400, 200);
            mensagem_de_alerta.setText("Selecione algum ingrediente!");
            Poupop.setVisible(true);
        } else if (ingre.equals("Adicionar novo")) {
            adicionarNovoIngrediente();
        } else if (quantidade == 0){
            Poupop.setSize(400, 200);
            mensagem_de_alerta.setText("Digite um valor para a quantidade!");
            Poupop.setVisible(true);
        } else if (unidade.equals("Unidade")){
            Poupop.setSize(400, 200);
            mensagem_de_alerta.setText("Selecione alguma unidade de medida!");
            Poupop.setVisible(true);
        }else{   
            //tabela_de_ingredientes
            DefaultTableModel model = (DefaultTableModel) tabela_de_ingredientes.getModel();
            Object[] linha = {ingre, quantidade, unidade};
            model.addRow(linha);
        }
    }//GEN-LAST:event_btAdicionarIngredienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaIngredientes();
        Poupop.add(mensagem_de_alerta);
    }//GEN-LAST:event_formWindowOpened

    private void txtCombo_Box_ingredientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCombo_Box_ingredientesFocusLost
        cbCodIngrediente.setSelectedIndex(txtCombo_Box_ingredientes.getSelectedIndex());
    }//GEN-LAST:event_txtCombo_Box_ingredientesFocusLost

    private void btExcluirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirIngredienteActionPerformed
        if(tabela_de_ingredientes.getSelectedRow() != -1){
            int linha = tabela_de_ingredientes.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tabela_de_ingredientes.getModel();
            model.removeRow(linha);}
    }//GEN-LAST:event_btExcluirIngredienteActionPerformed

    private void btAdicionarInstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarInstrucaoActionPerformed
        String instru = txtNomeInstru.getText();
        int tempo = Integer.parseInt(txtTempoInstru.getText());
        
        if (txtNomeInstru.getText().length()==0) { 
            Poupop.setSize(400, 200);
            mensagem_de_alerta.setText("Digite a Instrução!");
            Poupop.setVisible(true);
        } else if (tempo <= 0){
            Poupop.setSize(400, 200);
            mensagem_de_alerta.setText("Digite um valor para o tempo em minutos!");
            Poupop.setVisible(true);
        }else{   
            //tabela_de_ingredientes
            DefaultTableModel model = (DefaultTableModel) tabela_de_instrucoes.getModel();
            Object[] linha = {instru, tempo};
            model.addRow(linha);    
        }
    }//GEN-LAST:event_btAdicionarInstrucaoActionPerformed

    private void btExcluirInstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirInstrucaoActionPerformed
        if(tabela_de_instrucoes.getSelectedRow() != -1){
            int linha = tabela_de_instrucoes.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tabela_de_instrucoes.getModel();
            model.removeRow(linha);}
    }//GEN-LAST:event_btExcluirInstrucaoActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
       Poupop.setVisible(false);      
    }//GEN-LAST:event_OKActionPerformed

    public void carregaIngredientes(){
        String sql = "SELECT * from dbcooktok.tbingrediente";
        try {
            Connection conn = ConexaoFactory.getConexao();
            Statement stat = conn.createStatement();
            
            ResultSet result = stat.executeQuery(sql);
            while(result.next()){
                cbCodIngrediente.addItem(Integer.toString(result.getInt("pkcodingre"))) ;
                txtCombo_Box_ingredientes.addItem(result.getString("nomeingre"));
            }
            ConexaoFactory.close(conn,stat);
        } catch (SQLException throwables) {
            System.out.println("Erro ao exibir Ingrediente");
        } 
    }    
    
    public void adicionarNovoIngrediente(){
        Poupop.setSize(400, 200);
        mensagem_de_alerta.setText("Ainda NÃO foi programado, chame o Igor");
        Poupop.setVisible(true);
    }
    
    public static void main(String args[]) {
        //MASSA PARA TESTES 
        //INGREDIENTES
        Ingrediente ingre1 = new Ingrediente("Leite Condensado");
        Ingrediente ingre2 = new Ingrediente("Farinha de Trigo");
        Ingrediente ingre3 = new Ingrediente("Leite");
        Ingrediente ingre4 = new Ingrediente("Ovo");
        Ingrediente ingre5 = new Ingrediente("Manteiga");
        Ingrediente ingre6 = new Ingrediente("Oleo");
        Ingrediente ingre7 = new Ingrediente("Granulado");
        Ingrediente ingre8 = new Ingrediente("Creme de Leite");

        //String listaIngrediente[] = {ingre1.getNome_Ingred() , ingre2.getNome_Ingred(), ingre, ingre4, ingre5, ingre6, ingre7, ingre8};
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar_Ingrediente_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar_Ingrediente_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar_Ingrediente_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar_Ingrediente_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionar_Ingrediente_Receita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Salvar;
    private javax.swing.JButton OK;
    private javax.swing.JPanel PainelCabecalho;
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JPanel PainelIngredientes;
    private javax.swing.JPanel PainelInstrucoes;
    private javax.swing.JPanel PainelNomeReceita;
    private javax.swing.JPanel PainelRodapé;
    private javax.swing.JDialog Poupop;
    private javax.swing.JButton btAdicionarIngrediente;
    private javax.swing.JButton btAdicionarInstrucao;
    private javax.swing.JButton btExcluirIngrediente;
    private javax.swing.JButton btExcluirInstrucao;
    private javax.swing.JLabel cabecalho_Nome;
    private javax.swing.JComboBox<String> cbCodIngrediente;
    private javax.swing.JLabel descricao_indgredientes;
    private javax.swing.JLabel descricao_ingredientes_quantidade;
    private javax.swing.JLabel descricao_ingredientes_unidadedemedida;
    private javax.swing.JLabel descricao_nome_receita;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbInstrucao;
    private javax.swing.JLabel lbTempo;
    private javax.swing.JLabel mensagem_de_alerta;
    private javax.swing.JTable tabela_de_ingredientes;
    private javax.swing.JTable tabela_de_instrucoes;
    private javax.swing.JComboBox<String> txtCombo_Box_ingredientes;
    private javax.swing.JTextField txtIngrediente_Quantidade;
    private javax.swing.JTextArea txtNomeInstru;
    private javax.swing.JTextField txtNome_Receita;
    private javax.swing.JTextField txtTempoInstru;
    // End of variables declaration//GEN-END:variables
}
