/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ConexaoFactory;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author ester
 */
public class Tela_Inicio extends javax.swing.JFrame {
    private String[] vetorNome = new String[10];
    private String[] vetorCodigo = new String[10];
    private String fim;
    private Tela_Exec telaExec = new Tela_Exec();
    /**
     * Creates new form Tela_Ececucao
     */
    public Tela_Inicio() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        popup = new javax.swing.JDialog();
        mensagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_cabecalho = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel_Menu = new javax.swing.JPanel();
        cbFiltro = new javax.swing.JComboBox<>();
        detalhes_pesquisar = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbReceita2 = new javax.swing.JLabel();
        lbReceita3 = new javax.swing.JLabel();
        lbReceita4 = new javax.swing.JLabel();
        lbReceita6 = new javax.swing.JLabel();
        lbReceita7 = new javax.swing.JLabel();
        lbReceita8 = new javax.swing.JLabel();
        lbReceita9 = new javax.swing.JLabel();
        lbReceita1 = new javax.swing.JLabel();
        lbReceita0 = new javax.swing.JLabel();
        lbReceita5 = new javax.swing.JLabel();
        btAdicionarReceita = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        btAvancar = new javax.swing.JButton();

        jLabel13.setBackground(new java.awt.Color(110, 198, 202));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Receita 1");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout popupLayout = new javax.swing.GroupLayout(popup.getContentPane());
        popup.getContentPane().setLayout(popupLayout);
        popupLayout.setHorizontalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        popupLayout.setVerticalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Tela_Exec"); // NOI18N
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(8, 151, 157));

        jPanel_cabecalho.setBackground(new java.awt.Color(8, 151, 157));
        jPanel_cabecalho.setForeground(new java.awt.Color(8, 151, 157));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Cook Tok");

        jPanel_Menu.setBackground(new java.awt.Color(204, 171, 216));
        jPanel_Menu.setForeground(new java.awt.Color(204, 171, 216));

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Ingrediente", "Nome", "Tempo" }));

        detalhes_pesquisar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        detalhes_pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        detalhes_pesquisar.setText("Pesquisar");

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MenuLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MenuLayout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(detalhes_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detalhes_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(204, 171, 216));
        jPanel3.setForeground(new java.awt.Color(204, 171, 216));

        jPanel6.setBackground(new java.awt.Color(110, 198, 202));

        lbReceita2.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita2.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita2.setText("Receita 1");
        lbReceita2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita2MouseClicked(evt);
            }
        });

        lbReceita3.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita3.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita3.setText("Receita 1");
        lbReceita3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita3MouseClicked(evt);
            }
        });

        lbReceita4.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita4.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita4.setText("Receita 1");
        lbReceita4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita4MouseClicked(evt);
            }
        });

        lbReceita6.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita6.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita6.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita6.setText("Receita 1");
        lbReceita6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita6MouseClicked(evt);
            }
        });

        lbReceita7.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita7.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita7.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita7.setText("Receita 1");
        lbReceita7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita7MouseClicked(evt);
            }
        });

        lbReceita8.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita8.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita8.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita8.setText("Receita 1");
        lbReceita8.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita8MouseClicked(evt);
            }
        });

        lbReceita9.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita9.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita9.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita9.setText("+");
        lbReceita9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita9MouseClicked(evt);
            }
        });

        lbReceita1.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita1.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita1.setText("Receita 2");
        lbReceita1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita1MouseClicked(evt);
            }
        });

        lbReceita0.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita0.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita0.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita0.setText("Receita 1");
        lbReceita0.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbReceita0MouseEntered(evt);
            }
        });

        lbReceita5.setBackground(new java.awt.Color(110, 198, 202));
        lbReceita5.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbReceita5.setForeground(new java.awt.Color(255, 255, 255));
        lbReceita5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReceita5.setText("Receita 1");
        lbReceita5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 151, 157)));
        lbReceita5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbReceita5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbReceita5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReceita5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbReceita0, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbReceita5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbReceita6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbReceita1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbReceita2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbReceita7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbReceita3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbReceita8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbReceita4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbReceita9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbReceita3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbReceita4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbReceita8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbReceita9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(lbReceita2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbReceita7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(lbReceita6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbReceita0, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbReceita1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbReceita5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btAdicionarReceita.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btAdicionarReceita.setText("Adicionar \nReceitas");
        btAdicionarReceita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAdicionarReceita.setInheritsPopupMenu(true);
        btAdicionarReceita.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btAdicionarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_cabecalhoLayout = new javax.swing.GroupLayout(jPanel_cabecalho);
        jPanel_cabecalho.setLayout(jPanel_cabecalhoLayout);
        jPanel_cabecalhoLayout.setHorizontalGroup(
            jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_cabecalhoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAdicionarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_cabecalhoLayout.setVerticalGroup(
            jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cabecalhoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(btAdicionarReceita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btAvancar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btAvancar.setText(">");
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btAvancar)
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbReceita0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita0MouseEntered
       
    }//GEN-LAST:event_lbReceita0MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btAdicionarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarReceitaActionPerformed

        new TelaAdicionar_Receita().setVisible(true);
    }//GEN-LAST:event_btAdicionarReceitaActionPerformed

    private void lbReceita0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita0MouseClicked
        if (vetorCodigo[0] != ""){
            telaExec.setCodReceita(vetorCodigo[0]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita0MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        carregaReceita("0");
    }//GEN-LAST:event_formWindowActivated

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        carregaReceita(fim);
    }//GEN-LAST:event_btAvancarActionPerformed

    private void lbReceita1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita1MouseClicked
        if (vetorCodigo[1] != ""){
            telaExec.setCodReceita(vetorCodigo[1]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita1MouseClicked

    private void lbReceita2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita2MouseClicked
        if (vetorCodigo[2] != ""){
            telaExec.setCodReceita(vetorCodigo[2]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita2MouseClicked

    private void lbReceita3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita3MouseClicked
        if (vetorCodigo[3] != ""){
            telaExec.setCodReceita(vetorCodigo[3]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita3MouseClicked

    private void lbReceita4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita4MouseClicked
        if (vetorCodigo[4] != ""){
            telaExec.setCodReceita(vetorCodigo[4]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita4MouseClicked

    private void lbReceita5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita5MouseClicked
        if (vetorCodigo[5] != ""){
            telaExec.setCodReceita(vetorCodigo[5]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita5MouseClicked

    private void lbReceita6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita6MouseClicked
        if (vetorCodigo[6] != ""){
            telaExec.setCodReceita(vetorCodigo[6]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita6MouseClicked

    private void lbReceita7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita7MouseClicked
        if (vetorCodigo[7] != ""){
            telaExec.setCodReceita(vetorCodigo[7]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita7MouseClicked

    private void lbReceita8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita8MouseClicked
        if (vetorCodigo[8] != ""){
            telaExec.setCodReceita(vetorCodigo[8]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita8MouseClicked

    private void lbReceita9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReceita9MouseClicked
        if (vetorCodigo[9] != ""){
            telaExec.setCodReceita(vetorCodigo[9]);
            telaExec.setVisible(true);
        }
    }//GEN-LAST:event_lbReceita9MouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    
    }//GEN-LAST:event_formWindowGainedFocus
    
    public void carregaReceita(String começo){
        
        for(int i = 0; i<10; i++){
            vetorNome[i]="";
            vetorCodigo[i]="";
        }
        String sql = "SELECT * from dbcooktok.tbreceita where pkcodreceita >"+começo+" limit 10";
        try {
            Connection conn = ConexaoFactory.getConexao();
            Statement stat = conn.createStatement();
            
            ResultSet result = stat.executeQuery(sql);
            
            int i=0;
            while(result.next()){
                vetorNome[i] = result.getString("nomereceita") ;
                vetorCodigo[i] = result.getString("pkcodreceita");
                i++;
            }
            
            if (vetorCodigo[9] != ""){
                fim = vetorCodigo[9];
            }else{
                fim = "0";
            }
            lbReceita0.setText(vetorNome[0]);
            lbReceita1.setText(vetorNome[1]);
            lbReceita2.setText(vetorNome[2]);
            lbReceita3.setText(vetorNome[3]);
            lbReceita4.setText(vetorNome[4]);
            lbReceita5.setText(vetorNome[5]);
            lbReceita6.setText(vetorNome[6]);
            lbReceita7.setText(vetorNome[7]);
            lbReceita8.setText(vetorNome[8]);
            lbReceita9.setText(vetorNome[9]);
            
            ConexaoFactory.close(conn,stat);
        } catch (SQLException throwables) {
            System.out.println("Erro ao exibir Receitas");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarReceita;
    private javax.swing.JButton btAvancar;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JLabel detalhes_pesquisar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_cabecalho;
    private javax.swing.JLabel lbReceita0;
    private javax.swing.JLabel lbReceita1;
    private javax.swing.JLabel lbReceita2;
    private javax.swing.JLabel lbReceita3;
    private javax.swing.JLabel lbReceita4;
    private javax.swing.JLabel lbReceita5;
    private javax.swing.JLabel lbReceita6;
    private javax.swing.JLabel lbReceita7;
    private javax.swing.JLabel lbReceita8;
    private javax.swing.JLabel lbReceita9;
    private javax.swing.JLabel mensagem;
    private javax.swing.JDialog popup;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
